name: Flatpak

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  flatpak:
    name: Build Flatpak
    runs-on: ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          lfs: 'true'

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: Deecy.flatpak
          manifest-path: build-aux/io.github.Senryoku.Deecy.yml
          cache-key: flatpak-builder-${{ github.sha }}

      - name: Upload Flatpak Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Deecy-flatpak
          path: Deecy.flatpak